name: Build LaTeX document
on:
  - pull_request

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Compile LaTeX slides
        uses: xu-cheng/latex-action@v4
        with:
          root_file: stash.tex
          args: '-pdf -file-line-error -interaction=nonstopmode -shell-escape'
          working_directory: docs/slides
      - name: Compile LaTeX paper
        uses: xu-cheng/latex-action@v4
        with:
          root_file: stash.tex
          args: '-pdf -file-line-error -interaction=nonstopmode -shell-escape'
          working_directory: docs/paper
